apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
  labels:
    app: config-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: config-app
        image: docker.io/library/caassampleapi:latest # Use your Docker image
        imagePullPolicy: Never
        volumeMounts:
        - name: shared-config
          mountPath: /app/config
      - name: config-sidecar
        image: docker.io/library/configsidecar:latest # Replace with your sidecar image
        imagePullPolicy: Never
        volumeMounts:
        - name: config-source
          mountPath: /sidecar/config # Where the sidecar writes the config
        - name: shared-config
          mountPath: /app/config # Where the main app reads the config
      volumes:
        - name: shared-config
          emptyDir: {} 
        - name: config-source
          configMap:
            name: my-config # ConfigMap name